//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlhaObraAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int ID { get; set; }
        public int ID_Obra { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Tipo { get; set; }
        public byte[] Conteudo { get; set; }
    
        public virtual Obra Obra { get; set; }
        public virtual TipoRegistro TipoRegistro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
