<html>
    <title>API - JSON - Hackthon #IziBUS</title>

    <body>
        <h1>API - JSON - Hackthon #IziBUS</h1>
        <h2>Enviar dados por POST</h2>

        <h3>Usuários - Integração Governo</h3>

        <p>
            <strong>Salvar usuário - http://app/usuarios/salvar</strong>
        <p>Envia: POST(login, senha)</p>
        <p>Retorno:</p>
        <code>{"mensagem":"Usuario cadastrado com sucesso","status":true}</code>
        <p>Erros:</p>
        <code>{"mensagem":"Login j\u00e1 existe.","status":false}</code>
    </p>
    <p>
        <strong>Listar todos os usuarios - http://app/usuarios/listar_todos</strong><br>
        <code>[{"idusuario":"2","login":"beto_richa","senha":"1334fcee3c919b0725b7f2766afbbe85","situacao":"A"},{"idusuario":"3","login":"carlos","senha":"1334fcee3c919b0725b7f2766afbbe85","situacao":"A"},{"idusuario":"4","login":"carss","senha":"1334fcee3c919b0725b7f2766afbbe85","situacao":"A"},{"idusuario":"1","login":"marcos_santos","senha":"b38d5524d1ccfc11b182e9bae3e20657","situacao":"A"}]</code>
    </p>
    
    <h3>Localização - Geolocalização e informação sobre o transporte</h3>
        <p>
            <strong>Salvar localizacao - http://app/listar_geos/salvar</strong>
        </p>
        <p>Envia: POST(linha, latitude, longitude, texto_situacao)</p>
        <p>Retorno:</p>
        <code>{"mensagem":"Localização cadastrado com sucesso","status":true}</code>
        <p>Erros:</p>
        <code>{"mensagem":"erro ao salvar localizacao","status":false}</code>
        <p>
            <strong>Listar localizacao - http://app/listar_geos/listar_todos</strong>
        </p>
        <p>Envia: POST()</p>
         <p>Retorno:</p>
        <code>[
            {
                "linha": "469 - CENTRO POLIT\u00c9CNICO",
                "latitude": "-25.3490948",
                "longitude": "-49.1935856",
                "informacao": "#BusaoLotado"
            },
            {
                "linha": "469 - CENTRO POLIT\u00c9CNICO",
                "latitude": "-25.7790948",
                "longitude": "-48.1935856",
                "informacao": "#SentadoNoBusao"
            },
            {
                "linha": "216 - CABRAL \/ PORT\u00c3O",
                "latitude": "4546545",
                "longitude": "121231321",
                "informacao": "#BusaoLivreTop"
            }
        ]</code>
        
</body>



</html>